TestUngDung/Areas/Admin/Controllers/LoaiSPController.cs
using ModelEF.Dao;
using ModelEF.Model;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;

namespace TestUngDung.Areas.Admin.Controllers
{
    public class LoaiSPController : BaseController
    {
        // GET: Admin/MenuCategory
        public ActionResult Index(string searchString, int page = 1, int pagesize = 5)
        {
            var user = new MenuTypeDao();
            var model = user.List(searchString);
            @ViewBag.SearchString = searchString;
            return View(model.ToPagedList(page, pagesize));
        }

        public ActionResult Detais(string id)
        {
            var dao = new MenuTypeDao();
            var rs = dao.Find(id);
            return View(rs);

        }
        public string SlugName(string text)
        {
            for (int i = 32; i < 48; i++)
            {
                text = text.Replace(((char)i).ToString(), " ");
            }
            text = text.ToLower();
            text = text.Replace(".", "-");
            text = text.Replace(" ", "-");
            text = text.Replace(",", "-");
            text = text.Replace(";", "-");
            text = text.Replace(":", "-");
            Regex regex = new Regex(@"\p{IsCombiningDiacriticalMarks}+");
            string SlugName = text.Normalize(System.Text.NormalizationForm.FormD);
            return regex.Replace(SlugName, String.Empty).Replace('\u0111', 'd').Replace('\u0110', 'D');
        }
        [HttpGet]
        public ActionResult Create()
        {

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(loai_sp Entity)
        {

            if (ModelState.IsValid)
            {

                var dao = new MenuTypeDao();
                string rs = dao.Insert(Entity);
                if (!string.IsNullOrEmpty(rs))
                {

                    return RedirectToAction("Index", "LoaiSPs");
                }

                return View();
            }
            else
            {

                return View();
            }

        }
        [HttpGet]
        public ActionResult Update(string id)
        {
            var dao = new MenuTypeDao();
            var rs = dao.Find(id);

            return View(rs);

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Update(loai_sp Entity)
        {


            if (ModelState.IsValid)
            {
                Entity.ID = SlugName(Entity.ID);

                if (new MenuTypeDao().Update(Entity))
                {
                    setAlert("Cập nhật dữ liệu thành công!", "success");
                    return RedirectToAction("Index", "LoaiSPs");
                }
                else
                {
                    ModelState.AddModelError("", "Không thể cập nhật thông tin! Vui lòng kiểm tra lại!");
                }
            }
            return View(Entity);
        }
        [HttpGet]
        public ActionResult Delete(string id)
        {
            var dao = new MenuTypeDao().Delete(id);
            setAlert("Xoá bản ghi thành công!", "success");
            return RedirectToAction("Index", "QLKhachHang");
        }
    }
}

TestUngDung/Areas/Admin/Controllers/LoginController.cs
using ModelEF.Dao;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TestUngDung.Areas.Admin.Models;
using TestUngDung.common;

namespace TestUngDung.Areas.Admin.Controllers
{
    public class LoginController : Controller
    {
        // GET: Admin/Login
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(LoginModel user)
        {
            if (ModelState.IsValid)
            {
                var dao = new UserDao();
                var rs = dao.Login(user.UserName, Encryptor.EncryptorMD5(user.Password));
                if (rs == 0)
                {
                    ModelState.AddModelError("", "Tài Khoản Không Tồn Tại");
                }
                else
                {
                    if (rs == -1)
                    {
                        ModelState.AddModelError("", "Mật Khẩu Không Đúng ");
                    }
                    else
                    {
                        if (rs == 2)
                        {
                            ModelState.AddModelError("", "Tài khoản bị chặn");
                        }
                        else
                        {
                            if (rs == -2)
                            {
                                ModelState.AddModelError("", "Chỉ Đăng nhập bằng tài Khoản ADmin?");
                            }
                            else
                            {
                                /*ModelState.AddModelError("", "Đăng nhập thành công");*/
                                Session.Add(Constants.USER_SESSION, user);
                                return RedirectToAction("Index", "Home");
                            }
                        }
                    }
                }
            }
            return View("Index");
        }
    }
}

TestUngDung/Areas/Admin/Views/Shared/_Layout.cshtml
@using TestUngDung.Areas.Admin.Models;
@using TestUngDung.common
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>QUẢN LÝ BÁN HÀNG</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <style>
        .navbar-inverse {
            background-color: #1eb026;
            border-color: #b43bff;
        }

            .navbar-inverse .navbar-brand {
                color: #000;
            }

            .navbar-inverse .navbar-nav > li > a {
                color: #000;
            }
    </style>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <a href="@Url.Action("Index", "Home")" class="navbar-brand">Trang Chủ</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="@Url.Action("Index", "SanPham")">Sản Phẩm</a></li>
                    <li>@Html.ActionLink("Loại sản phẩm", "Index", "LoaiSP")</li>
                    <li>@Html.ActionLink("Khách hàng", "Index", "KhachHang")</li>


                </ul>
                @{ var session = (LoginModel)Session[Constants.USER_SESSION]; }
                @if (session != null)
                {
    <ul class="nav navbar-nav navbar-right">
        <li>
            <a>Hello @session.UserName</a>
        </li>
        <li><a href="@Url.Action("Logout", "Home")">Đăng xuất</a></li>
    </ul> }
else
{
<ul class="nav navbar-nav navbar-right">
    @*<li>@Html.ActionLink("Register", "Register", "Account", routeValues: null, htmlAttributes: new { id = "registerLink" })</li>*@
    <li>@Html.ActionLink("Đăng nhập", "Index", "Login", routeValues: null, htmlAttributes: new { id = "loginLink" })</li>
</ul>}

            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Công ty điện thoại Hồ Minh Thắng</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>